---
# vars file for linux-image-upgradation
   old_image_version : xp-2.1.0.0
   image_version : test-1.0
   image_url : "http://10.12.40.60/internal-share/xp-kernels/linux-image-3.16.7-test-1.0.tar.gz"
   debfile : linux-image-3.16.7
   image_upgrade : true
   image_roleback : false
   image_roleback_debfiles: "linux-image-3.16.7-test-1.0"

