---

##
##----------------------------------------------------------
## Playbook Name: reboot-system.yml
##----------------------------------------------------------
## Purpose:  This playbook will reboot the system
##----------------------------------------------------------
## Prerequisites: Please ensure that host inventory is correct
##----------------------------------------------------------
## Author :                Last modified Date:
##----------------------------------------------------------
##


- name: Restart machine
  shell: sleep 2 && shutdown -r now "rebooting ..."
  async: 1
  poll: 0
  ignore_errors: yes

- name: Waiting for machine to come back up
  local_action: wait_for host={{ inventory_hostname }} state=started delay=10 timeout=300 connect_timeout=15
